### ISSUE TITLE
Artifact download fails from https://raw.githubusercontent.com

### ISSUE THREAD

**Issue by GregMefford** [nerves-project/nerves#143]
This issue was reported by um404 in the Slack channel.

It appears that, in this case, the problem is a missing `CONTENT-DISPOSITION` header, but this error message also isn't helpful. We should improve the error-handling as well as solving this issue with a missing header.

### Current behavior

```bash
$ MIX_TARGET=zynq mix firmware

Mix environment
  MIX_TARGET:   zynq
  MIX_ENV:      dev

warning: variable "target" is unused
  mix.exs:59

==> nerves_system_zynq
Generated nerves_system_zynq app
|Elixir.Nerves.Package.Providers.HTTP| Downloading Artifact nerves_system_zynq-0.1.0.arm_unknown_linux_gnueabihf.tar.gz
  From Location:
    https://github.com/uldza/nerves_system_zynq/raw/master/nerves_system_zynq.tar.gz

** (EXIT from #PID<0.70.0>) an exception was raised:
    ** (MatchError) no match of right hand side value: nil
        (nerves) lib/nerves/utils/http_client.ex:59: Nerves.Utils.HTTPClient.handle_info/2
        (stdlib) gen_server.erl:601: :gen_server.try_dispatch/4
        (stdlib) gen_server.erl:667: :gen_server.handle_msg/5
        (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3

10:48:18.598 [error] GenServer #PID<0.186.0> terminating
** (MatchError) no match of right hand side value: nil
    (nerves) lib/nerves/utils/http_client.ex:59: Nerves.Utils.HTTPClient.handle_info/2
    (stdlib) gen_server.erl:601: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:667: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: {:http, {#Reference<0.0.5.965>, :stream_start, [{'cache-control', 'max-age=300'}, {'connection', 'keep-alive'}, {'date', 'Mon, 03 Jul 2017 07:48:19 GMT'}, {'via', '1.1 varnish'}, {'accept-ranges', 'bytes'}, {'etag', '"e148ead325b500bb7d369cdba5da8e109b4f443b"'}, {'vary', 'Authorization,Accept-Encoding'}, {'content-length', '75989986'}, {'content-type', 'application/octet-stream'}, {'expires', 'Mon, 03 Jul 2017 07:53:19 GMT'}, {'content-security-policy', 'default-src \'none\'; style-src \'unsafe-inline\''}, {'strict-transport-security', 'max-age=31536000'}, {'x-content-type-options', 'nosniff'}, {'x-frame-options', 'deny'}, {'x-xss-protection', '1; mode=block'}, {'x-geo-block-list', []}, {'x-github-request-id', '5BDA:2020:35D119:385214:5959F6C1'}, {'x-served-by', 'cache-ams4420-AMS'}, {'x-cache', 'MISS'}, {'x-cache-hits', '0'}, {'x-timer', 'S1499068097.199341,VS0,VE2692'}, {'access-control-allow-origin', '*'}, {'x-fastly-request-id', '60fc2a44492072e249eff033259dfdeb6c67cace'}]}}
State: %{buffer: "", buffer_size: 0, caller: {#PID<0.70.0>, #Reference<0.0.5.907>}, content_length: 0, filename: "", number_of_redirects: 1, url: "https://raw.githubusercontent.com/uldza/nerves_system_zynq/master/nerves_system_zynq.tar.gz"}
```

### Expected behavior

See the relevant code here: https://github.com/nerves-project/nerves/blob/master/lib/nerves/utils/http_client.ex#L49

* The download should succeed if the requested file exists.
* The file name should be inferred from the URL if the server does not indicate it in any way we can predict.
* Improve error-handling to display error or warning messages when things don't match what we expect, instead of (or at least in addition to) crashing the process.

**Comment by mobileoverlord** [comment]
Fixed in v0.9.0
