### ISSUE TITLE
Resolving Nerves artifacts... fails in version 0.10

### ISSUE THREAD

**Issue by NickNeck** [nerves-project/nerves#245]
### Environment
* Erlang version: 20
* Elixir version: 1.6.1
* Operating system: macOS
### Current behavior

After updating to `{:nerves, "~> 0.10", runtime: false},` I get the following error.
```
Resolving Nerves artifacts...
  Resolving nerves_toolchain_arm_unknown_linux_gnueabihf
  => Downloading https://github.com/nerves-project/toolchains/releases/download/v0.13.1/nerves_toolchain_arm_unknown_linux_gnueabihf-darwin_x86_64-0.13.1-E5B7BE50E7CBA5AD7F65E30D3CC8700933F5D066A8188D8BAF5E1EEC6DE124CF.tar.xz
|==================================================| 100% (49 / 49) MB
** (MatchError) no match of right hand side value: {:error, "tar: could not chdir to '/Users/nick/.nerves/artifacts/nerves_toolchain_arm_unknown_linux_gnueabihf-darwin_x86_64-0.13.1'\n\n"}
    (nerves) lib/nerves/artifact/cache.ex:22: Nerves.Artifact.Cache.put/2
    (nerves) lib/mix/tasks/nerves.artifact.get.ex:59: Mix.Tasks.Nerves.Artifact.Get.get_artifact/2
    (elixir) lib/enum.ex:737: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:737: Enum.each/2
    (mix) lib/mix/task.ex:314: Mix.Task.run_task/3
    lib/mix/tasks/nerves/deps.get.ex:13: Mix.Tasks.Nerves.Deps.Get.run/1
    (mix) lib/mix/task.ex:314: Mix.Task.run_task/3
    (mix) lib/mix/task.ex:348: Mix.Task.run_alias/3
```
I guess the directory has to be `/User/nick/.nerves/artifacts`

For my project, I had to go back to this deps. 
```
%{
  "distillery": {:hex, :distillery, "1.5.2", "eec18b2d37b55b0bcb670cf2bcf64228ed38ce8b046bb30a9b636a6f5a4c0080", [:mix], [], "hexpm"},
  "nerves": {:hex, :nerves, "0.9.2", "7f006ffd16901059ca687b763b370e075c05ec30f6c22962f84a359fc192eed8", [:mix], [{:distillery, "~> 1.4", [hex: :distillery, repo: "hexpm", optional: false]}], "hexpm"},
  "nerves_system_br": {:hex, :nerves_system_br, "0.17.0", "f7c0d1b6b11e9a1c187b17f2401a00956bebd5c45946bfe2a332ad26ecbf18f9", [:mix], [], "hexpm"},
  "nerves_system_linter": {:hex, :nerves_system_linter, "0.3.0", "84e0f63c8ac196b16b77608bbe7df66dcf352845c4e4fb394bffd2b572025413", [:mix], [], "hexpm"},
  "nerves_toolchain_arm_unknown_linux_gnueabihf": {:hex, :nerves_toolchain_arm_unknown_linux_gnueabihf, "0.13.0", "998a206d011351be34a95f63362c8195a4e81be81496206390258442166a8353", [:mix], [{:nerves, "~> 0.9", [hex: :nerves, repo: "hexpm", optional: false]}, {:nerves_toolchain_ctng, "~> 1.3", [hex: :nerves_toolchain_ctng, repo: "hexpm", optional: false]}], "hexpm"},
  "nerves_toolchain_ctng": {:hex, :nerves_toolchain_ctng, "1.3.0", "37486214f043e695b256785647f33e00b0ea4dcec2dfacd6e2c044c15d656e9d", [:mix], [{:nerves, "~> 0.9", [hex: :nerves, repo: "hexpm", optional: false]}], "hexpm"},
}
```

**Comment by mobileoverlord** [comment]
I ran into this yesterday and I believe that I know how you got here. I believe what happened is that you built the tool chain locally on Mac OS therefore there is a broken symlink in the artifact directory that is pointing to an ejected disk image.
 
To fix this in the short term, you can delete the file that it’s saying it cannot chdir to and try again.

This is happening for two reasons

1. Nerves bootstrap will now only add aliases if MIX_TARGET is set. This means that you likely ran mix compile on the kiosk system without setting a target which then also compiled the tool chain instead of downloading it. We should just always alias deps.get and deps.update to prevent this.

2. macOS has to build toolchains in a disk image due to filesystem limitations. We need to handle the broken symlink and force the artifact creation.

I’ll have a fix for these up soon. Thanks for reporting them 😁
